In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd # para leer datos
import sklearn.ensemble # para el random forest
import sklearn.model_selection # para split train-test
import sklearn.metrics # para calcular el f1-score
%matplotlib inline

In [115]:
# Carga datos
data = pd.read_csv('{}year.arff'.format(1), skiprows=69, header=None)
n_x,n_y=np.shape(data)

In [116]:
def getIndexes(dfObj, value):
    ''' Get index positions of value in dataframe i.e. dfObj.'''
 
    listOfPos = list()
    result = dfObj.isin([value])
    seriesObj = result.any()
    columnNames = list(seriesObj[seriesObj == True].index)
    for col in columnNames:
        rows = list(result[col][result[col] == True].index)
        for row in rows:
            listOfPos.append((row, col))
    return listOfPos

In [117]:
listOfPositions = getIndexes(data,"?")

#for i in range(len(listOfPositions)):
#    print('Position ', i, ' (Row index , Column Name) : ', listOfPositions[i])

In [119]:
listOfPositions=np.array(listOfPositions)
data2 = data.drop(listOfPositions[:,1],axis=1)
np.shape(data2)

12        18       19        22        29        30        38  \
0     0.166600  0.149420  43.3700  0.119980  0.117880  0.149420  0.128040   
1     0.158350  0.152000  87.9810  0.123040  0.269690  0.152000  0.121300   
2     0.244350  0.236100  73.1330  0.189960  0.419290  0.238150  0.241140   
3     0.094257  0.071428  79.7880  0.062782  0.143430  0.071428  0.088995   
4     0.121820  0.115530  57.0450  0.115530  0.278840  0.115530  0.122310   
...        ...       ...      ...       ...       ...       ...       ...   
7022  0.020881  0.004526   4.9656  0.004526  0.093539  0.004526  0.007891   
7023  0.037092 -0.012158  34.4360 -0.010802  0.466270 -0.012158 -0.007072   
7024  0.014722  0.003342  34.8620  0.001762  0.138060  0.003342  0.004048   
7025 -0.030657 -0.087322   9.1932 -0.098825  2.011900  0.015220 -0.232720   
7026  0.015420  0.005139  24.2750  0.005034  0.316370  0.014846  0.015677   

            41       42        43        48        54        55       57  \
0     0.128040  114.420   71.0500  0.110850  348690.0  0.121960  0.87804   
1     0.145950  199.490  111.5100  0.139610    2304.6  0.121300  0.85300   
2     0.231170  165.510   92.3810  0.222930    6332.7  0.241140  0.76599   
3     0.088995  180.770  100.9800  0.066165   20545.0  0.054015  0.94598   
4     0.122310  141.620   84.5740  0.116010    3186.6  0.134850  0.86515   
...        ...      ...       ...       ...       ...       ...      ...   
7022  0.007891    9.572    4.6064 -0.008464   -2732.8  0.011909  0.98809   
7023 -0.007072   85.314   50.8790 -0.056322   -2557.1 -0.011082  1.01110   
7024  0.004048   94.936   60.0740 -0.007331    4826.9  0.008258  0.99174   
7025  0.015220  125.360  116.1700 -0.041444   -1633.0 -0.232720  0.98788   
7026  0.016558  111.720   87.4430  0.006277      42.0  0.015705  0.97443   

           61  64  
0      82.658   0  
1     107.350   0  
2     134.270   0  
3      86.435   0  
4     127.210   0  
...       ...  ..  
7022   31.268   1  
7023   94.092   1  
7024   51.019   1  
7025  261.850   1  
7026  108.640   1  

[7027 rows x 16 columns]

In [94]:
data[data.any == 0.20055]#.index[0]
#pd.Index(data).get_loc("?")
data.find("?")

AttributeError: 'DataFrame' object has no attribute 'find'

In [ ]:
data=np.array(data)#print(data[64])
skip=np.array(np.where("?"== data))
            #            skip=np.append(skip,j)
print(np.shape(skip))
#print(data)
print(np.delete(data,skip,1))

In [ ]:
for i in range(len(data[:,0])): 
    for j in range(len(data[0,:])): 
        data[i,j]=float(data[i,j])

In [3]:
features=[]
for i in range(1,len(data[:,n_y-1])+1):
    features=np.append(features,"Attr{}".format(i))

TypeError: '(slice(None, None, None), 64)' is an invalid key

In [ ]:
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(
                                    data[:,:n_y-2], data[:,n_y-1], test_size=0.5)

In [ ]:
clf = sklearn.ensemble.RandomForestClassifier(n_estimators=10, max_features='sqrt')
clf

In [ ]:
n_trees = np.arange(1,400,25)
f1_train = []
f1_test = []
feature_importance = np.zeros((len(n_trees), len(features)))

for i, n_tree in enumerate(n_trees):
    clf = sklearn.ensemble.RandomForestClassifier(n_estimators=n_tree, max_features='sqrt')
    clf.fit(X_train, y_train)
    f1_train.append(sklearn.metrics.f1_score(y_train, clf.predict(X_train)))
    f1_test.append(sklearn.metrics.f1_score(y_test, clf.predict(X_test)))
    feature_importance[i, :] = clf.feature_importances_

In [ ]:
X_train

In [ ]:
y_train

In [ ]:
float(data[0,0])

In [17]:
print(data[10])

['0.24001' '0.44355' '0.18835' '1.44' '-21.165' '-0.9319' '0.24001'
 '1.2545' '4.7447' '0.55645' '0.24227' '0.56072' 0.1951 '0.24001' '174.89'
 '2.087' '2.2545' '0.24001' 0.050585000000000005 22.026999999999997
 '1.6856' '0' 0.050585000000000005 '?' '-0.63075' '2.087' '0' '0.491'
 '3.2184' 0.091302 0.1082 '50.94' '7.1653' '6.9146' '0.01533' '4.7447' '?'
 '0.55645' 0.0032310000000000004 '0.12237' '0.021562' 0.0
 43.388000000000005 21.361 '0.83822' '0.7711' '34.076' '-0.6857' -0.14452
 '1.3897' '0.42804' '0.13956' '1.4505' '1.4505' 311.43 0.35359 '0.43132'
 0.64794 '0' '16.571' '17.087' 32.928000000000004 '11.085' '12.369' 0]


In [33]:
array(data).index("?")

NameError: name 'array' is not defined

In [39]:
np.where("?"== data)

(array([   1,    1,    2, ..., 7024, 7024, 7026]),
 array([23, 36, 23, ..., 26, 36, 20]))

In [52]:
a=np.array(["a","b","c"])
np.where(a=="c")

(array([2]),)

In [55]:
a=np.array([[1,2,1],[1,2,1]])
np.where(a==1)

(array([0, 0, 1, 1]), array([0, 2, 0, 2]))