In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd # para leer datos
import sklearn.ensemble # para el random forest
import sklearn.model_selection # para split train-test
import sklearn.metrics # para calcular el f1-score
%matplotlib inline

In [85]:
# Carga datos
data = pd.read_csv('{}year.arff'.format(1), skiprows=69, header=None)
n_x,n_y=np.shape(data)
data

0        1         2        3        4          5          6   \
0       0.20055  0.37951   0.39641   2.0472   32.351    0.38825    0.24976   
1       0.20912  0.49988   0.47225   1.9447   14.786          0    0.25834   
2       0.24866  0.69592   0.26713   1.5548  -1.1523          0    0.30906   
3      0.081483  0.30734   0.45879   2.4928   51.952    0.14988   0.092704   
4       0.18732  0.61323    0.2296   1.4063  -7.3128    0.18732    0.18732   
...         ...      ...       ...      ...      ...        ...        ...   
7022   0.018371   0.4741  -0.13619  0.60839  -18.449   0.018371   0.018371   
7023  -0.013359  0.58354  -0.02265  0.92896  -42.232  -0.013359  -0.015036   
7024   0.006338  0.50276   0.43923   1.8736   9.7417   0.006338   0.012022   
7025  -0.041643   0.8481  -0.12852  0.57485  -121.92          0  -0.036795   
7026   0.014946  0.94648   0.03211   1.0363  -20.581          0    0.01526   

            7        8         9   ...        55         56       57  \
0       1.3305   1.1389   0.50494  ...  0.121960    0.39718  0.87804   
1      0.99601   1.6996   0.49788  ...  0.121300    0.42002  0.85300   
2      0.43695    1.309   0.30408  ...  0.241140    0.81774  0.76599   
3       1.8661   1.0571   0.57353  ...  0.054015    0.14207  0.94598   
4       0.6307   1.1559   0.38677  ...  0.134850    0.48431  0.86515   
...        ...      ...       ...  ...       ...        ...      ...   
7022   0.97203   1.0121   0.46084  ...  0.011909   0.039866  0.98809   
7023   0.56289  0.98904   0.32847  ... -0.011082  -0.040671  1.01110   
7024   0.98356   1.0083   0.49449  ...  0.008258   0.012817  0.99174   
7025   0.17901  0.42138   0.15182  ... -0.232720   -0.27429  0.98788   
7026  0.056357   2.9694  0.053341  ...  0.015705    0.28021  0.97443   

            58      59      60       61      62       63  64  
0     0.001924   8.416  5.1372   82.658  4.4158   7.4277   0  
1            0  4.1486  3.2732  107.350     3.4   60.987   0  
2      0.69484  4.9909   3.951  134.270  2.7185   5.2078   0  
3            0  4.5746  3.6147   86.435  4.2228   5.5497   0  
4      0.12444  6.3985  4.3158  127.210  2.8692    7.898   0  
...        ...     ...     ...      ...     ...      ...  ..  
7022   0.27414  73.505  79.237   31.268  11.673   5.1489   1  
7023   0.80592  10.599   7.174   94.092  3.8792   1.7572   1  
7024         0   10.47  6.0759   51.019  7.1542   62.001   1  
7025    3.5931  39.703   3.142  261.850  1.3939  0.51005   1  
7026    1.1792  15.036  4.1741  108.640  3.3599   35.118   1  

[7027 rows x 65 columns]

In [91]:
np.shape(data[data.any == 0.20055])#.index[0]
#pd.Index(data).get_loc("?")

(7027,)

In [ ]:
data=np.array(data)#print(data[64])
skip=np.array(np.where("?"== data))
            #            skip=np.append(skip,j)
print(np.shape(skip))
#print(data)
print(np.delete(data,skip,1))

In [ ]:
for i in range(len(data[:,0])): 
    for j in range(len(data[0,:])): 
        data[i,j]=float(data[i,j])

In [3]:
features=[]
for i in range(1,len(data[:,n_y-1])+1):
    features=np.append(features,"Attr{}".format(i))

TypeError: '(slice(None, None, None), 64)' is an invalid key

In [ ]:
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(
                                    data[:,:n_y-2], data[:,n_y-1], test_size=0.5)

In [ ]:
clf = sklearn.ensemble.RandomForestClassifier(n_estimators=10, max_features='sqrt')
clf

In [ ]:
n_trees = np.arange(1,400,25)
f1_train = []
f1_test = []
feature_importance = np.zeros((len(n_trees), len(features)))

for i, n_tree in enumerate(n_trees):
    clf = sklearn.ensemble.RandomForestClassifier(n_estimators=n_tree, max_features='sqrt')
    clf.fit(X_train, y_train)
    f1_train.append(sklearn.metrics.f1_score(y_train, clf.predict(X_train)))
    f1_test.append(sklearn.metrics.f1_score(y_test, clf.predict(X_test)))
    feature_importance[i, :] = clf.feature_importances_

In [ ]:
X_train

In [ ]:
y_train

In [ ]:
float(data[0,0])

In [17]:
print(data[10])

['0.24001' '0.44355' '0.18835' '1.44' '-21.165' '-0.9319' '0.24001'
 '1.2545' '4.7447' '0.55645' '0.24227' '0.56072' 0.1951 '0.24001' '174.89'
 '2.087' '2.2545' '0.24001' 0.050585000000000005 22.026999999999997
 '1.6856' '0' 0.050585000000000005 '?' '-0.63075' '2.087' '0' '0.491'
 '3.2184' 0.091302 0.1082 '50.94' '7.1653' '6.9146' '0.01533' '4.7447' '?'
 '0.55645' 0.0032310000000000004 '0.12237' '0.021562' 0.0
 43.388000000000005 21.361 '0.83822' '0.7711' '34.076' '-0.6857' -0.14452
 '1.3897' '0.42804' '0.13956' '1.4505' '1.4505' 311.43 0.35359 '0.43132'
 0.64794 '0' '16.571' '17.087' 32.928000000000004 '11.085' '12.369' 0]


In [33]:
array(data).index("?")

NameError: name 'array' is not defined

In [39]:
np.where("?"== data)

(array([   1,    1,    2, ..., 7024, 7024, 7026]),
 array([23, 36, 23, ..., 26, 36, 20]))

In [52]:
a=np.array(["a","b","c"])
np.where(a=="c")

(array([2]),)

In [55]:
a=np.array([[1,2,1],[1,2,1]])
np.where(a==1)

(array([0, 0, 1, 1]), array([0, 2, 0, 2]))